// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhclwhvbtzcxlhvlwxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoY2x3aHZidHpjeGxodmx3eHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzcyNzksImV4cCI6MjA3MDE1MzI3OX0.GQ4lqWLxzXm_3P6kyK48bwPAD8GR5wVGDwt7ueoznx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});